name: Linux CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-gcc:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt update && sudo apt install -y cmake build-essential
    
    - name: Configure
      run: |
        mkdir -p build_gcc_${{ matrix.build_type }}
        cd build_gcc_${{ matrix.build_type }}
        cmake .. -DCMAKE_CXX_COMPILER=g++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: |
        cd build_gcc_${{ matrix.build_type }}
        cmake --build .

  build-clang:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake build-essential clang
    
    - name: Configure
      run: |
        mkdir -p build_clang_${{ matrix.build_type }}
        cd build_clang_${{ matrix.build_type }}
        cmake .. -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
    
    - name: Build
      run: |
        cd build_clang_${{ matrix.build_type }}
        cmake --build .
